[build]
    command = "npn run build"
    functions = "functions"
    publish = 'dist'

[dev]
    framework = "#custom"
    command =  "npm run dev"
    targetPort = 8080
    port = 5000
    publish = "dist"
    autoLaunch = false